apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connected-host-cluster-manifests
  namespace: argocd
  labels:
    feature.demos.loft.sh: connected-host-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/{REPLACE_ORG_NAME}/{REPLACE_REPO_NAME}
    targetRevision: HEAD
    path: vcluster-use-cases/connected-host-cluster/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: p-vcluster-flux-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true    
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m
